version: "3"
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  hobbymate_db:
    image: postgres:14.7-alpine
    container_name: hobbymate_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5099:5432
  hobbymate_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hobbymate_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
    depends_on:
      - hobbymate_db
  hobbymate_test:
    image: hobbymate-hobbymate_app
    container_name: hobbymate_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
    networks:
      - test
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - hobbymate_db
